from django.conf.urls import url

from . import views

app_name = 'metro'
urlpatterns = [
    url(r'^$', 
        views.simulation_manager, name='simulation_manager'),
    url(r'^(?P<simulation_id>[0-9]+)/$', 
        views.simulation_view, name='simulation_view'),
    url(r'^(?P<simulation_id>[0-9]+)/save$', 
        views.simulation_view_save, name='simulation_view_save'),
    url(r'^(?P<simulation_id>[0-9]+)/edit$', 
        views.simulation_view_edit, name='simulation_view_edit'),
    url(r'^howto$', 
        views.how_to, name='how_to'),
    url(r'^contributors$', 
        views.contributors, name='contributors'),
    url(r'^disqus$', 
        views.disqus, name='disqus'),
    url(r'^(?P<simulation_id>[0-9]+)/demand/$',
        views.demand_view, name='demand_view'),
    url(r'^(?P<simulation_id>[0-9]+)/demand/add$',
        views.usertype_add, name='usertype_add'),
    url(r'^(?P<simulation_id>[0-9]+)/demand/(?P<demandsegment_id>[0-9]+)/edit/$',
        views.usertype_edit, name='usertype_edit'),
    url(r'^(?P<simulation_id>[0-9]+)/demand/(?P<demandsegment_id>[0-9]+)/edit/save/$',
        views.usertype_edit_save, name='usertype_edit_save'),
    url(r'^(?P<simulation_id>[0-9]+)/demand/(?P<demandsegment_id>[0-9]+)/delete/$',
        views.usertype_delete, name='usertype_delete'),
    url(r'^(?P<simulation_id>[0-9]+)/demand/(?P<demandsegment_id>[0-9]+)/view/$',
        views.usertype_view, name='usertype_view'),
    url(r'^(?P<simulation_id>[0-9]+)/network/$',
        views.network_view, name='network_view'),
    url(r'^(?P<simulation_id>[0-9]+)/run/(?P<run_id>[0-9]+)/network$',
        views.network_view_run, name='network_view_run'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/$',
        views.matrix_main, name='matrix_main'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/view/$',
        views.matrix_view, name='matrix_view'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/edit/$',
        views.matrix_edit, name='matrix_edit'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/import/$',
        views.matrix_import, name='matrix_import'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/export/$',
        views.matrix_export, name='matrix_export'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/save/$',
        views.matrix_save, name='matrix_save'),
    url(r'^(?P<simulation_id>[0-9]+)/matrices/(?P<demandsegment_id>[0-9]+)/reset/$',
        views.matrix_reset, name='matrix_reset'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/$',
        views.pricing_main, name='pricing_main'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/view/$',
        views.pricing_view, name='pricing_view'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/edit/$',
        views.pricing_edit, name='pricing_edit'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/save/$',
        views.pricing_save, name='pricing_save'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/export/$',
        views.pricing_export, name='pricing_export'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/import/$',
        views.pricing_import, name='pricing_import'),
    url(r'^(?P<simulation_id>[0-9]+)/pricing/(?P<demandsegment_id>[0-9]+)/reset/$',
        views.pricing_reset, name='pricing_reset'),
    url(r'^copy$',
        views.copy_simulation, name='copy_simulation'),
    url(r'^add/action$',
        views.simulation_add_action, name='simulation_add_action'),
    url(r'^(?P<simulation_id>[0-9]+)/delete$',
        views.simulation_delete, name='simulation_delete'),
    url(r'^(?P<simulation_id>[0-9]+)/run/action$',
        views.simulation_run_action, name='simulation_run_action'),
    url(r'^(?P<simulation_id>[0-9]+)/run/(?P<run_id>[0-9]+)/stop$',
        views.simulation_run_stop, name='simulation_run_stop'),
    url(r'^(?P<simulation_id>[0-9]+)/run/(?P<run_id>[0-9]+)$',
        views.simulation_run_view, name='simulation_run_view'),
    url(r'^(?P<simulation_id>[0-9]+)/run_list$',
        views.simulation_run_list, name='simulation_run_list'),
    url(r'^(?P<simulation_id>[0-9]+)/run/(?P<run_id>[0-9]+)/link_output$',
        views.simulation_run_link_output, name='simulation_run_link_output'),
    url(r'^(?P<simulation_id>[0-9]+)/run/(?P<run_id>[0-9]+)/user_output$',
        views.simulation_run_user_output, name='simulation_run_user_output'),
    url(r'^register$',
        views.register, name='register'),
    url(r'^register/action$',
        views.register_action, name='register_action'),
    url(r'^login/error$',
        views.login_view, {'login_error': True}, name='login'),
    url(r'^login$',
        views.login_view, name='login'),
    url(r'^login/action$',
        views.login_action, name='login_action'),
    url(r'^logout$',
        views.logout_action, name='logout'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/$',
        views.public_transit_view, name='public_transit_view'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/list$',
        views.public_transit_list, name='public_transit_list'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/edit/save$',
        views.public_transit_edit_save, name='public_transit_edit_save'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/edit$',
        views.public_transit_edit, name='public_transit_edit'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/delete$',
        views.public_transit_delete, name='public_transit_delete'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/import$',
        views.public_transit_import, name='public_transit_import'),
    url(r'^(?P<simulation_id>[0-9]+)/public_transit/export$',
        views.public_transit_export, name='public_transit_export'),
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/$',
        views.object_view, name='object_view'),
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/list/$',
        views.object_list, name='object_list'),
    # For some reason object_edit_save must be declared before object_edit...
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/edit/save',
        views.object_edit_save, name='object_edit_save'),
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/edit/',
        views.object_edit, name='object_edit'),
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/delete/',
        views.object_delete, name='object_delete'),
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/import/',
        views.object_import, name='object_import'),
    url(r'^(?P<simulation_id>[0-9]+)/object/(?P<object>[a-z]+)/export/',
        views.object_export, name='object_export'),
]
