from django.urls import path

from . import views

app_name = 'metro'
urlpatterns = [
    path(r'', 
        views.simulation_manager, name='simulation_manager'),
    path(r'<simulation_id>[0-9]+/', 
        views.simulation_view, name='simulation_view'),
    path(r'<simulation_id>[0-9]+/save', 
        views.simulation_view_save, name='simulation_view_save'),
    path(r'<simulation_id>[0-9]+/edit', 
        views.simulation_view_edit, name='simulation_view_edit'),
    path(r'howto', 
        views.how_to, name='how_to'),
    path(r'tutorial', 
        views.tutorial, name='tutorial'),
    path(r'contributors', 
        views.contributors, name='contributors'),
    path(r'disqus', 
        views.disqus, name='disqus'),
    path(r'<simulation_id>[0-9]+/demand/',
        views.demand_view, name='demand_view'),
    path(r'<simulation_id>[0-9]+/demand/add',
        views.usertype_add, name='usertype_add'),
    path(r'<simulation_id>[0-9]+/demand/<demandsegment_id>[0-9]+/edit/',
        views.usertype_edit, name='usertype_edit'),
    path(r'<simulation_id>[0-9]+/demand/<demandsegment_id>[0-9]+/edit/save/',
        views.usertype_edit_save, name='usertype_edit_save'),
    path(r'<simulation_id>[0-9]+/demand/<demandsegment_id>[0-9]+/delete/',
        views.usertype_delete, name='usertype_delete'),
    path(r'<simulation_id>[0-9]+/demand/<demandsegment_id>[0-9]+/view/',
        views.usertype_view, name='usertype_view'),
    path(r'<simulation_id>[0-9]+/network/',
        views.network_view, name='network_view'),
    path(r'<simulation_id>[0-9]+/run/<run_id>[0-9]+/network',
        views.network_view_run, name='network_view_run'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/',
        views.matrix_main, name='matrix_main'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/view/',
        views.matrix_view, name='matrix_view'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/edit/',
        views.matrix_edit, name='matrix_edit'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/import/',
        views.matrix_import, name='matrix_import'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/export/',
        views.matrix_export, name='matrix_export'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/save/',
        views.matrix_save, name='matrix_save'),
    path(r'<simulation_id>[0-9]+/matrices/<demandsegment_id>[0-9]+/reset/',
        views.matrix_reset, name='matrix_reset'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/',
        views.pricing_main, name='pricing_main'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/view/',
        views.pricing_view, name='pricing_view'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/edit/',
        views.pricing_edit, name='pricing_edit'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/save/',
        views.pricing_save, name='pricing_save'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/export/',
        views.pricing_export, name='pricing_export'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/import/',
        views.pricing_import, name='pricing_import'),
    path(r'<simulation_id>[0-9]+/pricing/<demandsegment_id>[0-9]+/reset/',
        views.pricing_reset, name='pricing_reset'),
    path(r'copy',
        views.copy_simulation, name='copy_simulation'),
    path(r'add/action',
        views.simulation_add_action, name='simulation_add_action'),
    path(r'<simulation_id>[0-9]+/delete',
        views.simulation_delete, name='simulation_delete'),
    path(r'<simulation_id>[0-9]+/run/action',
        views.simulation_run_action, name='simulation_run_action'),
    path(r'<simulation_id>[0-9]+/run/<run_id>[0-9]+/stop',
        views.simulation_run_stop, name='simulation_run_stop'),
    path(r'<simulation_id>[0-9]+/run/<run_id>[0-9]+)',
        views.simulation_run_view, name='simulation_run_view'),
    path(r'<simulation_id>[0-9]+/run_list',
        views.simulation_run_list, name='simulation_run_list'),
    path(r'<simulation_id>[0-9]+/run/<run_id>[0-9]+/link_output',
        views.simulation_run_link_output, name='simulation_run_link_output'),
    path(r'<simulation_id>[0-9]+/run/<run_id>[0-9]+/user_output',
        views.simulation_run_user_output, name='simulation_run_user_output'),
    path(r'register',
        views.register, name='register'),
    path(r'register/action',
        views.register_action, name='register_action'),
    path(r'login/error',
        views.login_view, {'login_error': True}, name='login'),
    path(r'login',
        views.login_view, name='login'),
    path(r'login/action',
        views.login_action, name='login_action'),
    path(r'logout',
        views.logout_action, name='logout'),
    path(r'password_reset',
        views.PasswordResetView.as_view(), name='password_reset'),
    path(r'password_reset_done',
        views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'password_reset_confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(r'<simulation_id>[0-9]+/public_transit/',
        views.public_transit_view, name='public_transit_view'),
    path(r'<simulation_id>[0-9]+/public_transit/list',
        views.public_transit_list, name='public_transit_list'),
    path(r'<simulation_id>[0-9]+/public_transit/edit/save',
        views.public_transit_edit_save, name='public_transit_edit_save'),
    path(r'<simulation_id>[0-9]+/public_transit/edit',
        views.public_transit_edit, name='public_transit_edit'),
    path(r'<simulation_id>[0-9]+/public_transit/delete',
        views.public_transit_delete, name='public_transit_delete'),
    path(r'<simulation_id>[0-9]+/public_transit/import',
        views.public_transit_import, name='public_transit_import'),
    path(r'<simulation_id>[0-9]+/public_transit/export',
        views.public_transit_export, name='public_transit_export'),
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/',
        views.object_view, name='object_view'),
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/list/',
        views.object_list, name='object_list'),
    # For some reason object_edit_save must be declared before object_edit...
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/edit/save',
        views.object_edit_save, name='object_edit_save'),
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/edit/',
        views.object_edit, name='object_edit'),
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/delete/',
        views.object_delete, name='object_delete'),
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/import/',
        views.object_import, name='object_import'),
    path(r'<simulation_id>[0-9]+/object/<object>[a-z]+/export/',
        views.object_export, name='object_export'),
]
